# Generated by Django 3.0.3 on 2020-02-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('receiver_name', models.CharField(max_length=30)),
                ('receiver_address', models.CharField(max_length=100)),
                ('invoice_no', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateField()),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('other_amount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
